logging:
  file:
    path: logs
    name: mod-workflow.log
  level:
    com:
      zaxxer:
        hikari: INFO
    org:
      folio: INFO
      hibernate: INFO
      springframework: INFO

server:
  servlet:
    context-path: /
  port: 9001

spring:
  activemq.broker-url: tcp://localhost:61616
  application.name: mod-workflow
  data.rest:
    returnBodyOnCreate: true
    returnBodyOnUpdate: true

  sql:
    init:
      #platform: h2
      platform: postgres

  datasource:
    hikari:
      leakDetectionThreshold: 180000
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: ${DB_MAXPOOLSIZE:16}
    #driverClassName: org.h2.Driver
    #url: jdbc:h2:./target/mod-workflow;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #platform: h2
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:mod_workflow}
    platform: postgres

    username: ${DB_USERNAME:folio_admin}
    password: ${DB_PASSWORD:folio_admin}

  h2:
    console:
      enabled: false
      path: /h2console
      settings:
        web-allow-others: true

  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties.hibernate.jdbc.lob.non_contextual_creation: true
    generate-ddl: false
    hibernate.ddl-auto: none
    open-in-view: true
    show-sql: false
  profiles:
    active: default, messaging
  thymeleaf:
    mode: TEXT
    suffix: .sql

event:
  uploads:
    path: events
  queue:
    name: event.queue

tenant:
  header-name: X-Okapi-Tenant
  force-tenant: false
  default-tenant: diku
  initialize-default-tenant: true
  domain-packages:
    - org.folio.rest.workflow.components
    - org.folio.rest.workflow.model
  schema-scripts:

okapi:
  url: ${OKAPI_URL:http://localhost:9130}
  camunda:
    base-path: /
    rest-path: /rest

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /admin
  health:
    defaults:
      enabled: true
    readinessstate:
      enabled: true

info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
